on:
    pull_request:
        types: [labeled]

    issue_comment:
        types: [created, edited]


name: Run tests
jobs:
    test:
        if: ${{ contains(github.event.pull_request.title, '[ci skip]') == false &&
                contains(github.event.pull_request.title, '[CI SKIP]') == false &&
                github.event.label.name == 'run-ci' }}

        name: Tests
        runs-on: macos-latest

        strategy:
            matrix:
                destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8', 'platform=iOS Simulator,OS=13.1,name=iPhone 9']
                xcode: ['/Applications/Xcode_12.3.app/Contents/Developer']
        steps:

        - name: Checkout in merge commit
          uses: actions/checkout@v2

        - name: Bundle Install
          run: bundle install

        - name: Setup ruby
          uses: ruby/setup-ruby@v1
          with:
              bundler-cache: true

        - name: Dependencies
          run: bundle exec pod install
          env:
              DEVELOPER_DIR: ${{ matrix.xcode }}

        - name: Build and test
          run: bundle exec fastlane tests
          env:
              destination: ${{ matrix.destination }}
              DEVELOPER_DIR: ${{ matrix.xcode }}