name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle Install
      run: bundle install
    - name: Dependencies
      run: bundle exec pod install
    - name: Run tests
      run: bundle exec fastlane tests
